### ISSUE TITLE
 Not working in Monterey 12.3.1

### ISSUE THREAD

**Issue by kenanmike** [notDavid/alfred-better-dictionaries-tmp#1]
Hello is this updated for working in Monterey 12.3.1? That's my current version but this workflow is not working for me. I've correctly set up, Python 2 is all installed etc., but here's how it's not working:

https://user-images.githubusercontent.com/85374001/162732860-e5afb4c5-3daa-456a-8a25-34a0435e00b0.mov

**Comment by kenanmike** [comment]
You'll see there that there's no problem with the built in Alfred dictionary function

**Comment by notDavid** [comment]
Hi there @kenanmike , sorry about that. I have only shared a workaround that works for me. The Developer of the workflow, or someone else, has to upgrade the workflow to work with the new Python3, because Apple removed python2 support in macOS 12.3.

So until then, it will be bugged.
